name: mcumgr
description: Dart client for the mcumgr embedded device management protocol.
version: 0.0.5
repository: https://github.com/jkdhn/mcumgr-dart

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cbor: ^6.2.0
